// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileId } from "./FileId";
import type { JobId } from "./JobId";
import type { Segment } from "./Segment";
import type { Speaker } from "./Speaker";
import type { SpeakerSpan } from "./SpeakerSpan";

export interface EditorData { fileId: FileId, defaultJobId: JobId, jobIds: Array<JobId>, segments: Array<Segment>, speakers: Array<Speaker>, speakerSpans: Array<SpeakerSpan>, }