// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobId } from "./JobId";
import type { JobStatus } from "./JobStatus";
import type { Language } from "./Language";
import type { TranslationQuality } from "./TranslationQuality";

export interface FileJob { id: JobId, language: Language, quality: TranslationQuality, status: JobStatus, createdAt: string, }