// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileId } from "./FileId";
import type { FileJob } from "./FileJob";

export interface File { id: FileId, name: string, jobs: Array<FileJob>, }