//! This module was created largely using [whisper.cpp](https://github.com/ggerganov/whisper.cpp/blob/master/whisper.cpp) and `vim` macros

use clap::ValueEnum;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(TS, Clone, Debug, PartialEq, Eq, ValueEnum, Serialize, Deserialize, sqlx::Type)]
#[sqlx(rename_all = "lowercase")]
#[ts(export)]
pub enum Language {
    English,
    Chinese,
    German,
    Spanish,
    Russian,
    Korean,
    French,
    Japanese,
    Portuguese,
    Turkish,
    Polish,
    Catalan,
    Dutch,
    Arabic,
    Swedish,
    Italian,
    Indonesian,
    Hindi,
    Finnish,
    Vietnamese,
    Hebrew,
    Ukrainian,
    Greek,
    Malay,
    Czech,
    Romanian,
    Danish,
    Hungarian,
    Tamil,
    Norwegian,
    Thai,
    Urdu,
    Croatian,
    Bulgarian,
    Lithuanian,
    Latin,
    Maori,
    Malayalam,
    Welsh,
    Slovak,
    Telugu,
    Persian,
    Latvian,
    Bengali,
    Serbian,
    Azerbaijani,
    Slovenian,
    Kannada,
    Estonian,
    Macedonian,
    Breton,
    Basque,
    Icelandic,
    Armenian,
    Nepali,
    Mongolian,
    Bosnian,
    Kazakh,
    Albanian,
    Swahili,
    Galician,
    Marathi,
    Punjabi,
    Sinhala,
    Khmer,
    Shona,
    Yoruba,
    Somali,
    Afrikaans,
    Occitan,
    Georgian,
    Belarusian,
    Tajik,
    Sindhi,
    Gujarati,
    Amharic,
    Yiddish,
    Lao,
    Uzbek,
    Faroese,
    Haitian,
    Pashto,
    Turkmen,
    Nynorsk,
    Maltese,
    Sanskrit,
    Luxembourgish,
    Myanmar,
    Tibetan,
    Tagalog,
    Malagasy,
    Assamese,
    Tatar,
    Hawaiian,
    Lingala,
    Hausa,
    Bashkir,
    Javanese,
    Sundanese,
}

impl Language {
    pub fn all() -> Vec<Language> {
        vec![
            Language::English,
            Language::Chinese,
            Language::German,
            Language::Spanish,
            Language::Russian,
            Language::Korean,
            Language::French,
            Language::Japanese,
            Language::Portuguese,
            Language::Turkish,
            Language::Polish,
            Language::Catalan,
            Language::Dutch,
            Language::Arabic,
            Language::Swedish,
            Language::Italian,
            Language::Indonesian,
            Language::Hindi,
            Language::Finnish,
            Language::Vietnamese,
            Language::Hebrew,
            Language::Ukrainian,
            Language::Greek,
            Language::Malay,
            Language::Czech,
            Language::Romanian,
            Language::Danish,
            Language::Hungarian,
            Language::Tamil,
            Language::Norwegian,
            Language::Thai,
            Language::Urdu,
            Language::Croatian,
            Language::Bulgarian,
            Language::Lithuanian,
            Language::Latin,
            Language::Maori,
            Language::Malayalam,
            Language::Welsh,
            Language::Slovak,
            Language::Telugu,
            Language::Persian,
            Language::Latvian,
            Language::Bengali,
            Language::Serbian,
            Language::Azerbaijani,
            Language::Slovenian,
            Language::Kannada,
            Language::Estonian,
            Language::Macedonian,
            Language::Breton,
            Language::Basque,
            Language::Icelandic,
            Language::Armenian,
            Language::Nepali,
            Language::Mongolian,
            Language::Bosnian,
            Language::Kazakh,
            Language::Albanian,
            Language::Swahili,
            Language::Galician,
            Language::Marathi,
            Language::Punjabi,
            Language::Sinhala,
            Language::Khmer,
            Language::Shona,
            Language::Yoruba,
            Language::Somali,
            Language::Afrikaans,
            Language::Occitan,
            Language::Georgian,
            Language::Belarusian,
            Language::Tajik,
            Language::Sindhi,
            Language::Gujarati,
            Language::Amharic,
            Language::Yiddish,
            Language::Lao,
            Language::Uzbek,
            Language::Faroese,
            Language::Haitian,
            Language::Pashto,
            Language::Turkmen,
            Language::Nynorsk,
            Language::Maltese,
            Language::Sanskrit,
            Language::Luxembourgish,
            Language::Myanmar,
            Language::Tibetan,
            Language::Tagalog,
            Language::Malagasy,
            Language::Assamese,
            Language::Tatar,
            Language::Hawaiian,
            Language::Lingala,
            Language::Hausa,
            Language::Bashkir,
            Language::Javanese,
            Language::Sundanese,
        ]
    }
    pub fn whisper_str(&self) -> &'static str {
        match self {
            Language::English => "en",
            Language::Chinese => "zh",
            Language::German => "de",
            Language::Spanish => "es",
            Language::Russian => "ru",
            Language::Korean => "ko",
            Language::French => "fr",
            Language::Japanese => "ja",
            Language::Portuguese => "pt",
            Language::Turkish => "tr",
            Language::Polish => "pl",
            Language::Catalan => "ca",
            Language::Dutch => "nl",
            Language::Arabic => "ar",
            Language::Swedish => "sv",
            Language::Italian => "it",
            Language::Indonesian => "id",
            Language::Hindi => "hi",
            Language::Finnish => "fi",
            Language::Vietnamese => "vi",
            Language::Hebrew => "iw",
            Language::Ukrainian => "uk",
            Language::Greek => "el",
            Language::Malay => "ms",
            Language::Czech => "cs",
            Language::Romanian => "ro",
            Language::Danish => "da",
            Language::Hungarian => "hu",
            Language::Tamil => "ta",
            Language::Norwegian => "no",
            Language::Thai => "th",
            Language::Urdu => "ur",
            Language::Croatian => "hr",
            Language::Bulgarian => "bg",
            Language::Lithuanian => "lt",
            Language::Latin => "la",
            Language::Maori => "mi",
            Language::Malayalam => "ml",
            Language::Welsh => "cy",
            Language::Slovak => "sk",
            Language::Telugu => "te",
            Language::Persian => "fa",
            Language::Latvian => "lv",
            Language::Bengali => "bn",
            Language::Serbian => "sr",
            Language::Azerbaijani => "az",
            Language::Slovenian => "sl",
            Language::Kannada => "kn",
            Language::Estonian => "et",
            Language::Macedonian => "mk",
            Language::Breton => "br",
            Language::Basque => "eu",
            Language::Icelandic => "is",
            Language::Armenian => "hy",
            Language::Nepali => "ne",
            Language::Mongolian => "mn",
            Language::Bosnian => "bs",
            Language::Kazakh => "kk",
            Language::Albanian => "sq",
            Language::Swahili => "sw",
            Language::Galician => "gl",
            Language::Marathi => "mr",
            Language::Punjabi => "pa",
            Language::Sinhala => "si",
            Language::Khmer => "km",
            Language::Shona => "sn",
            Language::Yoruba => "yo",
            Language::Somali => "so",
            Language::Afrikaans => "af",
            Language::Occitan => "oc",
            Language::Georgian => "ka",
            Language::Belarusian => "be",
            Language::Tajik => "tg",
            Language::Sindhi => "sd",
            Language::Gujarati => "gu",
            Language::Amharic => "am",
            Language::Yiddish => "yi",
            Language::Lao => "lo",
            Language::Uzbek => "uz",
            Language::Faroese => "fo",
            Language::Haitian => "ht",
            Language::Pashto => "ps",
            Language::Turkmen => "tk",
            Language::Nynorsk => "nn",
            Language::Maltese => "mt",
            Language::Sanskrit => "sa",
            Language::Luxembourgish => "lb",
            Language::Myanmar => "my",
            Language::Tibetan => "bo",
            Language::Tagalog => "tl",
            Language::Malagasy => "mg",
            Language::Assamese => "as",
            Language::Tatar => "tt",
            Language::Hawaiian => "haw",
            Language::Lingala => "ln",
            Language::Hausa => "ha",
            Language::Bashkir => "ba",
            Language::Javanese => "jw",
            Language::Sundanese => "su",
        }
    }
}
